###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "test@test.ru",
    "username": "test-user",
    "password": "qwerty123",
    "first_name": "test",
    "last_name": "test",
} 