# Generated by Django 4.2.4 on 2023-09-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_shoppinglist_unique_shopping_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
