# Generated by Django 4.2.4 on 2023-09-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_tagsinrecipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'verbose_name': 'Рецепты, избранное', 'verbose_name_plural': 'Рецепты, избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'verbose_name': 'Ингредиенты в рецептах', 'verbose_name_plural': 'Ингдредиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
