# Generated by Django 3.2 on 2023-09-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-author__id'], 'verbose_name': 'Управление подписками', 'verbose_name_plural': 'Управление подписками'},
        ),
    ]
