# Generated by Django 3.2 on 2023-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_pair',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_not_user',
        ),
    ]
